apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: test2
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: test2
    version: v1.0.0
    applicationId: app_7108581e-4f42-4acb-8010-ffd9d1595c8b
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_fd76a64c-3758-4ccc-bd5c-2fb67cc234d0
    environmentName: test-env
  namespace: test23
