apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: qa-helm-amaan
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: qa-helm-amaan
    version: v1.0.0
    applicationId: app_ddea461b-1c7d-4597-8879-b0068624496f
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_28e0313c-7e56-4c3f-832c-99e620025894
    environmentName: staging
  namespace: common-project-testing-staging
