apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: ai-feature-suggestion-solution-testing-main
      imagePullPolicy: Always
      imageRegistry: docker.io/amaan02/ai-feature-suggestion-solution-testing
      imagePullSecretName: imagepull-docker
      credentialId: credential_5784dbe8-0a00-4fb0-adb9-e0f0b099fa19
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: ai-feature-suggestion-solution-testing
    version: v1.0.0
    applicationId: app_c01789ad-b47d-48af-8d5a-3409559e4d43
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_73c32f56-d735-4561-a850-7e39497abbe9
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: ai-feature-suggestion-solution-testing
  serviceType: ClusterIP
  version: v1.0.0
  namespace: common-project-testing-prod
