apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-12
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_28e0313c-7e56-4c3f-832c-99e620025894
    test: '512'
spec:
  groups:
    - name: ''
      rules:
        - alert: ''
          expr: ''
          annotations:
            summary: ''
            description: ''
          labels:
            '': ''
