apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 322a69c49e4c56d6a7c2e7bdef07878a05c4e614
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: ai-feature-qa-main
      imagePullPolicy: Always
      imageRegistry: docker.io/amaan02/ai-feature-qa
      imagePullSecretName: imagepull-docker
      credentialId: credential_5784dbe8-0a00-4fb0-adb9-e0f0b099fa19
      commitDetails:
        commitHash: 322a69c49e4c56d6a7c2e7bdef07878a05c4e614
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-12-23T12:20:25Z'
        commitMessage: Deploy AI-FEATURE-QA to dev
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: ai-feature-qa
    version: v1.0.0
    applicationId: app_da4b216d-fbad-4336-a371-677e8c8891c7
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: AI-FEATURE-QA
  serviceType: ClusterIP
  version: v1.0.0
  namespace: common-project-testing-dev
