apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-rule
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_fd76a64c-3758-4ccc-bd5c-2fb67cc234d0
    test: '512'
spec:
  groups:
    - name: rule-group-1
      rules:
        - alert: Test Alert
          expr: rate(http_requests_total[5m]) > 10
          annotations:
            summary: High number of requests
            description: More than 10 requests per second in the last 5 minutes
          labels:
            severity: warning
