apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: config-dev
  namespace: common-project-testing-dev
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
spec:
  data:
    IP_ADDRESS: ${{secret::secret_6c8178a5-3c6e-4766-8839-e8dab77280e7:}}
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
