apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: Test
  creationTimestamp: null
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
    Test: '123'
spec:
  groups:
    - name: ''
      rules:
        - alert: ''
          expr: ''
          annotations:
            summary: ''
            description: ''
          labels:
            '': ''
