apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: ai-feature-suggestion-solution-testing-v1-0-0
  labels:
    app: ai-feature-suggestion-solution-testing-v1-0-0
    applicationId: app_c01789ad-b47d-48af-8d5a-3409559e4d43
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_28e0313c-7e56-4c3f-832c-99e620025894
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-feature-suggestion-solution-testing-v1-0-0
