apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: main-ai-qa-testing-v1-0-0
    applicationId: app_d68568ab-e5ba-4c7a-8ed9-df91598c0e44
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_fd76a64c-3758-4ccc-bd5c-2fb67cc234d0
  name: main-ai-qa-testing-v1-0-0
spec:
  selector:
    app: main-ai-qa-testing-v1-0-0
