apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helmnew-v1-0-0
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    applicaitonId: app_5fec5a50-284e-46d6-8a96-8694273ea6f4
spec:
  interval: 1m0s
  url: https://github.com/JayaniJ00/test-service-project
  ref:
    branch: master
  secretRef:
    name: helmnew-v1-0-0-secret
