apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    applicationId: app_883ec4c3-bd0c-4849-88a9-02cf7e9bc077
    version: v1.0.0
    environmentId: env_73c32f56-d735-4561-a850-7e39497abbe9
  name: ai-suggestion-solution-qa-v1-0-0
spec:
  successfulJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      annotations: {}
      labels:
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
        applicationId: app_883ec4c3-bd0c-4849-88a9-02cf7e9bc077
        version: v1.0.0
        environmentId: env_73c32f56-d735-4561-a850-7e39497abbe9
    spec:
      template:
        metadata:
          labels:
            organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
            projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
            applicationId: app_883ec4c3-bd0c-4849-88a9-02cf7e9bc077
            version: v1.0.0
            environmentId: env_73c32f56-d735-4561-a850-7e39497abbe9
