apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-driven-retest-v1-0-0
  labels:
    app: repo-driven-retest-v1-0-0
    applicationId: app_6872cb06-4f01-483a-994c-a1a2e37e15a7
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: repo-driven-retest-v1-0-0
  template:
    metadata:
      labels:
        app: repo-driven-retest-v1-0-0
        applicationId: app_6872cb06-4f01-483a-994c-a1a2e37e15a7
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
