apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: test24-v1-0-0
    applicationId: app_dd12c52c-5c0d-4432-894f-2cab2f3febb9
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
  name: test24-v1-0-0
spec:
  selector:
    app: test24-v1-0-0
