apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-severity-v1-0-0
  labels:
    app: test-severity-v1-0-0
    applicationId: app_27860546-25d4-4cbd-a731-88e3b5aba0b8
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    environmentId: env_e5d8feaf-553c-4cd5-8f37-09e5b58df4be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-severity-v1-0-0
