apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: qa-helm-testing-16-v1-0-0
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    applicaitonId: app_ab643ddc-1cc5-4cf5-bc24-616a6b2f3a19
spec:
  interval: 1m0s
  url: https://github.com/amaan-02/basic-java-testing-project
  ref:
    branch: master
  secretRef:
    name: qa-helm-testing-16-v1-0-0-secret
