apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: ai-service-project-v1-0-0
  labels:
    app: ai-service-project-v1-0-0
    applicationId: app_3c38b217-db2d-4d42-ad04-3e45f3f029f9
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_28e0313c-7e56-4c3f-832c-99e620025894
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-service-project-v1-0-0
