apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-ai-app-v1-0-0
  labels:
    app: test-ai-app-v1-0-0
    applicationId: app_c6b2b947-4c9f-40a4-bdd4-0c7b8fdd24e3
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-ai-app-v1-0-0
