apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: qa-team-project-main
      imagePullPolicy: Always
      imageRegistry: docker.io/qa-team-project
      imagePullSecretName: imagepull-docker
      credentialId: credential_c245ad9e-61ae-4101-b97a-27b44de16e18
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: qa-team-project
    version: v1.0.0
    applicationId: app_aac5aab0-9b12-4725-8966-9ebb381c0ae0
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: qa-team-project
  serviceType: ClusterIP
  version: v1.0.0
  namespace: common-project-testing-dev
