apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: qa-team-project-v1-0-0
  labels:
    app: qa-team-project-v1-0-0
    applicationId: app_aac5aab0-9b12-4725-8966-9ebb381c0ae0
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qa-team-project-v1-0-0
