apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: testing-2-main
      imagePullPolicy: Always
      imageRegistry: docker.io/testing-2
      imagePullSecretName: imagepull-docker
      credentialId: credential_c245ad9e-61ae-4101-b97a-27b44de16e18
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: testing-2
    version: v1.0.0
    applicationId: app_1e5aa626-a4a7-420f-9888-75a443159a1d
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_28e0313c-7e56-4c3f-832c-99e620025894
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: testing-2
  serviceType: ClusterIP
  version: v1.0.0
  namespace: common-project-testing-staging
