apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 91bd183d4609ec75bcd59591f55964bc8ad3ad20
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: main-ai-qa-testing-main
      imagePullPolicy: Always
      imageRegistry: docker.io/amaan02/main-ai-qa-testing
      imagePullSecretName: imagepull-docker
      credentialId: credential_f9ceb9fb-c1d3-4b37-b2e1-fbc721f838f9
      commitDetails:
        commitHash: 91bd183d4609ec75bcd59591f55964bc8ad3ad20
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2025-01-14T09:53:45Z'
        commitMessage: Deploy pipeline-run to dev
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: main-ai-qa-testing
    version: v1.0.0
    applicationId: app_d68568ab-e5ba-4c7a-8ed9-df91598c0e44
    projectId: project_f9d8de1f-1e49-4d0a-8e49-657f15fd532b
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_d3c9b73e-8f9c-46aa-a8ef-fd6addc71a6b
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: main-ai-qa-testing
  serviceType: ClusterIP
  version: v1.0.0
  namespace: common-project-testing-dev
