apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_92ed9ac3-1a76-4a98-b613-8fb7c60c0731
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_92ed9ac3-1a76-4a98-b613-8fb7c60c0731
spec:
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_92ed9ac3-1a76-4a98-b613-8fb7c60c0731
  provider: docker
  secretRef: secret_10cdf75e-b4cf-4abc-b94d-71be6babff5d
